-- Add to qb-core/shared/items.lua
-- medicalbag usable item is registered by dg_emsjob server bridge

['medicalbag'] = {
    name = 'medicalbag',
    label = 'Medical Bag',
    weight = 220,
    type = 'item',
    image = 'medicalbag.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = 'A comprehensive medical kit for treating injuries and ailments.',
},

['bandage'] = {
    name = 'bandage',
    label = 'Bandage',
    weight = 100,
    type = 'item',
    image = 'bandage.png',
    unique = false,
    useable = false,
    shouldClose = true,
    combinable = nil,
    description = 'A simple bandage used to cover and protect wounds.',
},

['defibrillator'] = {
    name = 'defibrillator',
    label = 'Defibrillator',
    weight = 100,
    type = 'item',
    image = 'defibrillator.png',
    unique = false,
    useable = false,
    shouldClose = true,
    combinable = nil,
    description = 'Used for reviving patients.',
},

['tweezers'] = {
    name = 'tweezers',
    label = 'Tweezers',
    weight = 100,
    type = 'item',
    image = 'tweezers.png',
    unique = false,
    useable = false,
    shouldClose = true,
    combinable = nil,
    description = 'Precision tweezers for safely removing foreign objects from wounds.',
},

['burncream'] = {
    name = 'burncream',
    label = 'Burn Cream',
    weight = 100,
    type = 'item',
    image = 'burncream.png',
    unique = false,
    useable = false,
    shouldClose = true,
    combinable = nil,
    description = 'Specialized cream for treating minor burns and skin irritations.',
},

['suturekit'] = {
    name = 'suturekit',
    label = 'Suture Kit',
    weight = 100,
    type = 'item',
    image = 'suturekit.png',
    unique = false,
    useable = false,
    shouldClose = true,
    combinable = nil,
    description = 'Surgical tools and materials for stitching wounds.',
},

['icepack'] = {
    name = 'icepack',
    label = 'Ice Pack',
    weight = 200,
    type = 'item',
    image = 'icepack.png',
    unique = false,
    useable = false,
    shouldClose = true,
    combinable = nil,
    description = 'An ice pack used to reduce swelling and inflammation.',
},

['stretcher'] = {
    name = 'stretcher',
    label = 'Stretcher',
    weight = 200,
    type = 'item',
    image = 'stretcher.png',
    unique = false,
    useable = false,
    shouldClose = true,
    combinable = nil,
    description = 'A stretcher for transporting injured players.',
},

['emstablet'] = {
    name = 'emstablet',
    label = 'Ems tablet',
    weight = 200,
    type = 'item',
    image = 'emstablet.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = 'EMS dispatch tablet for distress calls.',
},
